#!/bin/bash

params=("$@")

filtered_params=()
software_version="v1.8.0"

printf '%s ' "${params[@]}"

# Extract software_version and filter ROS arguments
new_params=()
skip_next=false
for (( i=0; i<${#params[@]}; i++ )); do
    if $skip_next; then
        skip_next=false
        continue
    fi
    
    if [[ "${params[$i]}" == "--software_version" ]]; then
        software_version="${params[$((i+1))]}"
        skip_next=true
        continue
    elif [[ "${params[$i]}" == "--ros-args" || "${params[$i]}" == "--params-file" ]]; then
        skip_next=true
        continue
    elif [[ "${params[$i]}" == __node:=* || "${params[$i]}" == __log:=* ]]; then
        continue
    fi
    
    new_params+=("${params[$i]}")
done

printf "\nUsing software version: ${software_version}\n"

# Build the filtered parameters
filtered_params=("${new_params[@]}")

# Print the command (for debugging purposes)
XELA_PATH="$(rospack find xela_server_ros)/software/${software_version}/bin/server/AppRun"
echo "Running command: $XELA_PATH ${filtered_params[@]}"

# Execute the command
$XELA_PATH "${filtered_params[@]}"